Issues-1: Close
nikolaymatrosov/go-yc-serverless-snapshot pull request #2
Opened 2021-10-17 08:25 UTC by kurmanovd

Добавил имя и описание для снепшота

2021-10-25 13:44 UTC, nikolaymatrosov requested changes

2021-10-25 13:44 UTC, nikolaymatrosov commented on snapshot-disks.go
> +	snapshotDescription := fmt.Sprintf("Expiration:  %s", tm)
Может быть стоит использовать вместо timestamp более человекочитаемый формат даты, хотя бы в description?

2021-10-25 13:44 UTC, nikolaymatrosov commented on snapshot-disks.go
> +	snapshotName := createSnapshotParams.DiskName + "-" + expirationTs
Вы нигде не проверяете, что не вылезли за допустимую длину названия. Кажется 63 символа максимум.

2021-10-27 07:26 UTC, kurmanovd commented on snapshot-disks.go
> +	snapshotDescription := fmt.Sprintf("Expiration:  %s", tm)
В description попадает строка вида: "Expiration: 2021-11-01 03:05:19 +0000 UTC". Кажется, достаточно человекочитаемая...

2021-10-27 10:51 UTC, kurmanovd commented on snapshot-disks.go
> +	snapshotName := createSnapshotParams.DiskName + "-" + expirationTs
Да, это моя ошибка. Добавил проверку и перенёс expirationTs в начало имени, т.к. в противном случае есть вероятность получить не уникальное имя

2021-11-01 16:38 UTC, merged